"""Přidání kaskádového mazání do CartItem

Revision ID: 245ea1f5d7a0
Revises: f26fccac8667
Create Date: 2025-02-10 14:33:25.250684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245ea1f5d7a0'
down_revision = 'f26fccac8667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###
